# Generated by Django 4.2.6 on 2023-10-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('symbol', models.CharField(default=None, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('exchangeLogo', models.CharField(default='', max_length=120)),
                ('binance_funding', models.FloatField(default=0.0)),
                ('okx_funding', models.FloatField(default=0.0)),
                ('dydx_funding', models.FloatField(default=0.0)),
                ('bybit_funding', models.FloatField(default=0.0)),
                ('gate_funding', models.FloatField(default=0.0)),
                ('bitget_funding', models.FloatField(default=0.0)),
                ('coinex_funding', models.FloatField(default=0.0)),
                ('bingx_funding', models.FloatField(default=0.0)),
                ('other_exchange_sum', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='FundingFinal',
            fields=[
                ('symbol', models.CharField(default=None, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('binance_positive', models.IntegerField(default=0)),
                ('binance_balance', models.IntegerField(default=0)),
                ('binance_negative', models.IntegerField(default=0)),
                ('other_ex_positive', models.IntegerField(default=0)),
                ('other_ex_balance', models.IntegerField(default=0)),
                ('other_ex_negative', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FundingTop10Neg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neg_symbol', models.CharField(default='', max_length=10)),
                ('neg_value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FundingTop10Pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_symbol', models.CharField(default='', max_length=10)),
                ('pos_value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('chat_id', models.CharField(default=None, max_length=20, unique=True)),
                ('username', models.CharField(default=None, max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
