# Generated by Django 4.2.7 on 2023-11-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depth',
            fields=[
                ('type', models.CharField(default='Depth', max_length=12)),
                ('symbol', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('total_asks_volume', models.IntegerField(default=0)),
                ('total_bids_volume', models.IntegerField(default=0)),
                ('limit3', models.FloatField(default=0.0)),
                ('limit5', models.FloatField(default=0.0)),
                ('limit8', models.FloatField(default=0.0)),
                ('limit30', models.FloatField(default=0.0)),
            ],
        ),
    ]
